CREATE TABLE Product(
  Id INT NOT NULL PRIMARY KEY,
  Name NVARCHAR(250) NOT NULL
)

CREATE TABLE Category(
  Id INT NOT NULL PRIMARY KEY,
  Name NVARCHAR(250) NOT NULL
)

CREATE TABLE Product_Category_Link(
  Product INT NOT NULL FOREIGN KEY REFERENCES Product(Id) ON DELETE CASCADE,
  Category INT NOT NULL FOREIGN KEY REFERENCES Category(Id) ON DELETE CASCADE
)
